# 부서 번호가 10번인 EMP 부서의 
# EMPNO, ENAME, SAL, DEPTNO

# 부서 번호 20번인 부서의 
# EMPNO, ENAME, SAL, DEPTNO

# UNION 사용 < 합집합 개념> < UNION은 출력열 개수와 자료형이 같을 때 사용>

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 20;

# 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10;

# 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10;
