# P.313 데이터 정의어 (CREATE)
# DROP TABLE EMP_DDL; -> 생성된 TABLE을 삭제
CREATE TABLE EMP_DDL (
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9)
);

SELECT * FROM EMP_DDL;
# 삽입
INSERT INTO EMP_DDL (EMPNO, ENAME, JOB)
VALUES (1000, 'KING', 'MANAGER');
COMMIT;

SELECT * FROM PHONEBOOK;
DESC PHONEBOOK;
COMMIT;

INSERT INTO PHONEBOOK (ID, NAME, HP) VALUES (7, '을지문덕', '010-2222-2222');
COMMIT;

