#검색
SELECT * FROM employees;
DESCRIBE employees;

SELECT FIRST_NAME FROM employees;
SELECT LAST_NAME FROM employees;
SELECT FIRST_NAME, LAST_NAME FROM employees;

SELECT * FROM COUNTRIES;

SELECT country_name FROM countries;

SELECT * FROM employees;
SELECT FIRST_NAME, SALARY FROM employees
ORDER BY SALARY DESC;

# 사원정보
DESC emp;
# 부서정보
DESC DEPT;
# 사원 급여 정보
DESC SALGRADE;
# P.80
SELECT * FROM EMP;
SELECT EMPNO, ENAME, DEPTNO
FROM EMP;

# 1분 복습 P.81
SELECT * FROM EMP;
SELECT EMPNO, DEPTNO FROM EMP;

# 중복제거
SELECT DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP;

SELECT DISTINCT JOB, DEPTNO FROM EMP
ORDER BY DEPTNO;

SELECT ALL JOB, DEPTNO FROM EMP;

# P. 81 컬럼을 갖고 연산을 할 수 있는가?
SELECT ENAME, SAL*12+NVL(COMM, 0) AS 연봉, NVL(COMM, 0) FROM EMP;
