# JOIN <테이블의 결합>
SELECT * FROM DEPT;
SELECT EMPNO, ENAME, DEPTNO FROM EMP;

# JOIN -> M*N 연산
# DEPT 4개 * EMP 12개
SELECT * FROM EMP, DEPT;
SELECT COUNT(*) FROM EMP, DEPT;

# 실제 사용하는 JOIN 구문 8-2
SELECT EMPNO, ENAME, LOC FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO
;

# EMP 테이블 별칭을 E DEPT 별칭을 D로 하여
# EMP 테이블의 사원번호와 DEPT 테이블 부서의 이름이 출력되도록 JOIN 쿼리를 작성해 주세요
SELECT E.EMPNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

# 등가 조인
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME, D.LOC FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;


# Q1.급여(SAL)가 2000 초과인 사원들의 부서 정보, 사원 정보를 출력하세요
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO AND E.SAL >= 2000
ORDER BY E.DEPTNO;


# Q2. 각 부서별 평균 급여, 최대 급여, 최소 급여, 사원수 출력
SELECT D.DEPTNO, DNAME, TRUNC(AVG(E.SAL)), MAX(E.SAL), MIN(E.SAL), COUNT(*) FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME
ORDER BY D.DEPTNO;


