# SEQ
# 연습을 위한 테이블
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * FROM DEPT
        WHERE 1 <> 1;
        
# 테이블 생성 확인
SELECT * FROM DEPT_SEQUENCE;
DESC DEPT_SEQUENCE;

#SEQ 쿼리로 만들기
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 90
MINVALUE 0
NOCYCLE
CACHE 2;

# 시퀀스 확인
SELECT * FROM USER_SEQUENCES;
SELECT * FROM DEPT_SEQUENCE;

# 시퀀스 사용
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

# 시퀀스 번호를 확인하기
SELECT SEQ_DEPT_SEQUENCE .CURRVAL FROM DUAL;

# 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 3
MAXVALUE 99
CYCLE;

COMMIT;

# 시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;
