# SUM 함수 (EMP_TABLE의 직원 전체의 월급 합산)
SELECT SUM(SAL) FROM EMP;

# GROUP BY / ORDER BY 를 통해 ERROR 해결
SELECT DEPTNO, SUM(SAL) FROM EMP 
GROUP BY DEPTNO
ORDER BY DEPTNO;

# 잘못 이해 할 수 있는 Query문 <주의>
SELECT ENAME, SUM(SAL) FROM EMP
GROUP BY ENAME;

# Q. EMP TABLE 에 존재하는 직원의 수는?
SELECT COUNT(*) FROM EMP;

# EMP TABLE 에서 가장 높은 급여와 가장 낮은 급여를 출력
SELECT MAX(SAL), MIN(SAL) FROM EMP;

# 부서 번호가 20번인 사원의 입사 일 중 제일 오래된 입사일 출력
SELECT MIN(HIREDATE) FROM EMP
WHERE DEPTNO = 20;

# 30번 부서의 사원들의 평균 급여를 소수점 둘째자리 에서 반올림
SELECT ROUND(AVG(SAL),1) FROM EMP
WHERE DEPTNO = 30;

# 부서별 평균 급여를 소수점 둘째 자리 에서 반올림
SELECT DEPTNO, ROUND(AVG(SAL),1) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

# 부서 번호 및 직책별 평균 급여 정렬하기
SELECT DEPTNO, JOB, ROUND(AVG(SAL),1) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

# GROUP BY 절을 사용하여 부서 번호별 평균 추가 수당을 출력해 주세요.
SELECT DEPTNO, NVL(AVG(COMM), 0) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

# 평균 급여가 $2000 이상인 부서와 직책을 출력
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

# 급여가 3000이하 이면서 평균 급여가 2000 이상인 부서와 직책
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000 AND AVG(SAL) <= 3000
ORDER BY DEPTNO, JOB;

# WHERE 사용
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
WHERE SAL <= 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;
