# 제약 조건 이름 직접 지정
CREATE TABLE TABLE_NOTNULL2(
        LOGIN_ID VARCHAR2(20) CONSTRAINT CNAME_LOGID NOT NULL,
        LOGIN_PWI VARCHAR2(2) CONSTRAINT CNAME_LOGPW NOT NULL,
        TEL       VARCHAR(20)
);

# 제약조건 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
COMMIT;
DESC TABLE_NOTNULL2;


# 제약조건을 삽입하는 MODIFY
ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL NOT NULL);


# 제약 조건 이름 삭제
ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT SYS_C007011;


# 제약 조건 이름 추가하기
ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL CONSTRAINT CNAME_TEL NOT NULL);

# 중복되지 않는 값 UNIQUE
CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR(20) UNIQUE,
    LOGIN_PWD VARCHAR(20) NOT NULL,
    TEL       VARCHAR(20)
);

DESC TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
VALUES('2', 'USER_01', '010-1111-1111');

SELECT * FROM TABLE_UNIQUE;


CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL       VARCHAR2(20)
);


# P.381
DROP TABLE TABLE_NAME;
# 뒤에서 지정해주는것도 가능
CREATE TABLE TABLE_NAME(
    COL1 VARCHAR2(20),
    COL2 VARCHAR2(20),
    COL3 VARCHAR2(20),
    PRIMARY KEY (COL1),
    CONSTRAINT BBB UNIQUE(COL2)
);

# 일반적인 방법
CREATE TABLE TABLE_NAME(
    COL1 VARCHAR2(20) CONSTRAINT AAA PRIMARY KEY,
    COL2 VARCHAR2(20) NOT NULL,
    COL3 VARCHAR2(20)
);



# FOREIGN KEY 지정
# DEPT_FK, EMP_FK

CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPT_PK PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

CREATE TABLE EMP_FK(
    EMPNO NUMBER(4) CONSTRAINT EMP_PK PRIMARY KEY,
    DEPTNO NUMBER(2) CONSTRAINT CCC REFERENCES DEPT_FK (DEPTNO)
);

SELECT * FROM EMP_FK;
SELECT * FROM DEPT_FK;

DESC EMP_FK;
DESC DEPT_FK;

DROP TABLE DEPT_FK;

# 14 - 41 ~ 14 - 43 실습
INSERT INTO EMP_FK
VALUES(9999, 10);

INSERT INTO DEPT_FK
VALUES(10, 'TEST_DNAME', 'TEST_LOC');

SELECT * FROM EMP_FK;
SELECT * FROM DEPT_FK;
